### PR TITLE
Do not ignore SELECT command errors

### PR DESCRIPTION
**Pull request by link2xt**
If NO or BAD response is returned, return an error instead of Ok(Malibox::default()).

### CODE REVIEW

**Comment by link2xt** [comment]
This is needed to fix https://github.com/deltachat/deltachat-core-rust/issues/2676

**Comment by link2xt** [comment]
This is discovered during debugging https://github.com/deltachat/deltachat-core-rust/issues/2676

**Review by dignifiedquire — COMMENTED** [review]
any chance we can have a test?

**Comment by link2xt** [comment]
> any chance we can have a test?

I have added a test and checked that it fails without this change.

**Review by dignifiedquire — APPROVED** [review]

**Pull request merged**
